name: Docker Image CI

on:
  push:
    branches:
      - main
      - feature*
  pull_request:
    branches:
      - main
      - feature*
  workflow_dispatch:

jobs:
  Build-Run-Docker-Container:
    runs-on: ubuntu-latest
    steps:
    - name: Check the code out
      uses: actions/checkout@v3

    - name: Build container
      run: 'docker build . --file Dockerfile --tag python-energy:$(date +%Y%m%d)'

    - name: Start container
      run: 'docker run -d python-energy:$(date +%Y%m%d) && sleep 20'

    - name: Check Postgres image output
      run: PGPASSWORD=docker psql -h localhost -U docker -d energy -c '\dt'
