name: Docker Image CI

on:
  push:
    branches:
      - main
      - 'feature*'
  pull_request:
    branches:
      - main
      - 'feature*'

jobs:
  Build-Docker-Container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - run: docker build . --file Dockerfile --tag python-energy:$(date +%s)
    - name: Check Postgres image output
      run: |
        psql -h localhost -U docker -d energy -c '\dt'